version: '3.2'
services:
  bestwebshop-frontend:
    build:
      context: ./
      dockerfile: ./DockerfileFrontend
    ports:
      - "80:3000"
    networks:
      local_dev_net:
          aliases:
              - bestwebshop-frontend


networks:
  local_dev_net:
    driver: bridge